title: Chroma Ad-Blocker
description: Premium YouTube Ad-Blocker for Manifest V3. Bypass detections with style.

# Custom settings
logo: icons/icon128.png
baseurl: ""
url: "https://Dabrogost.github.io/YT-Chroma"

# Ensure assets are included
include: 
  - icons
  - assets
  - PRIVACY_POLICY.md
  - ToS.md
  - LICENSE.md
permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
